name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Java 8
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'	
        java-version: 8
